seafile:
  build: ./
  # image: tcoupin/seafile-sqlite
  # dockerfile: Dockerfile.rpi	
  # image: tcoupin/rpi-seafile-sqlite
  ports:
    - 8082:8082
    - 8000:8000
  volumes:
    - ./workspace:/mnt/seafile
    - ./workspace/logs:/seafile/logs
    - ./workspace/seafile-data:/seafile/seafile-data
    - ./workspace/seahub-data:/seafile/seahub-data
    - ./workspace/ccnet:/seafile/ccnet
    - ./workspace/conf:/seafile/conf
  command: bash -c "rm /seafile/seahub.db && ln -s /mnt/seafile/seahub.db && ./start.sh && tail -f /seafile/logs/seahub.log"
