seafile:
  image: tcoupin/rpi-seafile-sqlite
  ports:
    - 8082:8082
    - 8000:8000
  volumes:
    - /mnt/seafile:/mnt/seafile
    - /mnt/seafile/logs:/seafile/logs
    - /mnt/seafile/seafile-data:/seafile/seafile-data
    - /mnt/seafile/seahub-data:/seafile/seahub-data
    - /mnt/seafile/ccnet:/seafile/ccnet
    - /mnt/seafile/conf:/seafile/conf
  command: bash -c "rm /seafile/seahub.db && ln -s /mnt/seafile/seahub.db && ./start.sh && tail -f /seafile/logs/seahub.log"
